version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: calculator_db
    environment:
      POSTGRES_USER: calc_user
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: calculator_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - main
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "calc_user", "-d", "calculator_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  calculator:
    container_name: calculator
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - "local.env"
    environment:
      - CONFIG_PATH=/app/config/local.yaml
      - HTTP_PORT=8080
      - LOG_LEVEL=debug

      - PG_HOST=calculator_db
      - PG_PORT=5432
      - PG_USER=calc_user
      - PG_PASSWORD=pwd123
      - PG_DBNAME=calculator_db
      - PG_SSLMODE=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - main

volumes:
  postgres_data:

networks:
  main:
    name: main
    external: true
